### ISSUE TITLE
Release Notes v0.21.0 (formerly knonw as v0.20.1)

### ISSUE THREAD

**Issue by stylesuxx** [bird-sanctuary/bluejay#161]
# v0.21.0

## User notes
If you don't read anything else, read (and follow) at least this section!

* All pilots are suggested to check their tunes using their preferred method due to the improvements in zero crossing detection. If you are running a particularly aggressive tune (including some factory tunes and presets!), you should consider lowering your master multiplier for the first few flights.
* Startup power has been lowered to safe values for typical 4s-6s 5" ESCs and motors.
* If you experience problems with motors failing to start, read the [setup guide](https://github.com/bird-sanctuary/bluejay/wiki/Setup) to find suitable motor idle and startup power values for your quad.

## Bugfixes 
* Bootloader was using wrong keys leading to at state where it would not be possible to save settings or flash firmware. This was only an issue after flashing v0.20.0 via C2 interface. During regular updates via [esc-configurator.com](https://esc-configurator.com) the bootloader is not written and people will not be affected.
* When fixing 3D mode, startup motor protection was inadvertently disabled which unfortunately lead to a couple fried ESCs and AIOs.
* There was a bug where max startup power has been ignored. This is now fixed and will help prevent damage to motors/ESCs in cases where the motors are stuck. This bug is present in BlheliS and Bluejay up to 0.20.0. It has special relevance in crashes, where the motors can get stuck and power is high. This is especially true for various FC related crash Recovery features after for example clipping a gate.

## Quality of life improvements
* Massive code refactoring, everything has been refactored into smaller, more readable modules. (#99, #103, #104, #107, #116, #117, #119, #128)
* Auto formatting has been applied and preparations have been made to check for proper formatting in PRs. (#93)

## Safety features
* **EDT safety arm** ensures that the ESC will only arm after a valid EDT handshake. This will only work with flight controller firmware that support EDT functionality.
* Temp protection is **disabled** by default: Since temp protection has effectively not been working for a long time (probably ever), the default is no to be disabled to prevent users from running into issues where they are "losing power". If temp protection is enabled, make sure that the "power rating" setting is set correctly and best verify via EDT and temperature readout on Betaflight, that the Temperature values are in a sane range (around 50). (#95)
* Improved defaults for min/max startup power

## Misc
* Since the current dithering implementation does not do what it is promising to do, we opted to remove it
* New layouts have been added. We were running out of letters for new ESC layouts and thought we might just make it if no new layouts pop up, but this of course is not the case - so we future proofed this and added functionality for ESC layouts to have 2 characters instead of one. (#113)
* Add supporter section. (#85, #89, #139)

## Findings
A lot of the planned features for 0.20/0.21 needed to be postponed to a later release since they are not working in a satisfactory way:
* Dynamic and variable PWM has been somewhat successful but not fully satisfactory to us. It is wasting a lot of CPU cycles, CPU cycles we do not have
* The current dithering implementation is eating up a lot of CPU cycles and is a bit flawed since it is only applied to every DSHOT package instead of every PWM cycle. Testing has shown that there is little to no difference in having vs. not having dithering in the current implementation. We might in the future ditch dithering in favor of gaining some CPU cycles to get some other - for us - more important features implemented
* In process of experimenting with dynamic PWM we came to the conclusion that 96kHz mode is pretty much useless and we might get rid of it in the future. The resolution on 96kHz is 256 steps in the best case. Considering deadtime, (which needs to be subtracted) - having high dead times reduces this even further. 

## Known issues
* Based on initial testing, 3d mode appears to be having performance issues from the bugfixes for startup protection since 0.20 - as such **use of 3d mode cannot be advised**.

**Comment by stylesuxx** [comment]
RC1: [Bluejay_0.20.1-rc1.zip](https://github.com/bird-sanctuary/bluejay/files/12359650/Bluejay_0.20.1-rc1.zip)

**Comment by damosvil** [comment]
Please, also add that when bringing back bidireccional 3d mode startup motor protection was unadvertedly disabled in 0.20

**Comment by Prajwal-Koirala** [comment]
**Here's a summary of the key points from the release notes for Bluejay firmware version 0.20.1:**

**Bug Fixes:**

- **Bootloader Issue:** Resolved a critical bug that prevented saving settings or flashing firmware after flashing v0.20.0 via the C2 interface. Users who updated via esc-configurator.com are not affected.
- **Startup Motor Protection:** Reinstated startup motor protection, which was inadvertently disabled in v0.20.0, leading to potential hardware damage.
- **Max Startup Power Bug:** Fixed a bug that ignored max startup power settings, potentially causing motor/ESC damage in cases of stuck motors or during crash recovery. This bug was present in both BlheliS and Bluejay up to v0.20.0.

**Important Recommendations:**

- **Update to v0.20.1:** It's strongly recommended to update to v0.20.1 to address these critical bugs and ensure optimal protection of your hardware.
- **Set up Startup Power:** Carefully configure min/max startup power using the provided setup guide to minimize the risk of hardware damage. This is crucial for protecting your motors and ESCs.

**Additional Information:**

- **Affected Users:** Those who flashed v0.20.0 via the C2 interface should prioritize updating to v0.20.1.
- **ESC Configurator Users:** Users who updated via esc-configurator.com are not affected by the bootloader issue.
- **Crash Recovery and Stuck Motors:** The fixed max startup power bug is particularly relevant in crash scenarios or when motors become stuck, as it can help prevent excessive power application and subsequent hardware damage.

**Comment by stylesuxx** [comment]
@damosvil @hyp0dermik-code I updated the Changelog - this is now a bit of a mashup of the planned 0.20.0 and 0.21.0 version. This should pretty much reflect the develop branch at this point. Could you give it a read-over and let me know what should be changed?

**Comment by damosvil** [comment]
It seems good to me

**Comment by hyp0dermik-code** [comment]
Thoughts on changing the order to:
- User Notes (not sure if this is the right name for this section?)
- Bugfixes
- QoL
- Safety Features
- Misc
- Findings

Looking for feedback on the 'tuning notes' too - not sure how strongly this should be made. Based on my experience with introduced noise and high D Term noise I don't feel as if it needs to be particularly strong, merely a suggestion

Suggested changes as below:

User Notes:
- All pilots are suggested to check their tunes using their preferred method due to the improvements in zero crossing detection. If you are running a particularly aggressive tune (including some factory tunes and presets!), you should consider lowering your master multiplier for the first few flights.
- Startup power has been lowered to safe values for typical 4s-6s 5" ESCs and motors.
- If you experience problems with motors failing to start, read the [setup guide](https://github.com/bird-sanctuary/bluejay/wiki/Setup) to find suitable motor idle and startup power values for your quad.

Bugfixes: 
- ~~When fixing 3D mode, startup motor protection was inadvertently disabled which unfortunately lead to a couple fried ESCs and AIOs.~~ The bugfixes for startup motor protection appear to have an impact on 3d performance again - see **Known Issues**

Known issues:
- Based on initial testing, 3d mode appears to be having performance issues from the bugfixes for startup protection since 0.20
- As such use of 3d mode cannot be advised

**Comment by stylesuxx** [comment]
Thank you @hyp0dermik-code - I updated the initial post according to your suggestion

**Comment by hyp0dermik-code** [comment]
Can we add the following to the top

Huge thanks to all testers, who combined have flown over 1250 packs on 0.21RC alone

And corrections:
(two seperate lines, should not be crossed out)
-  When fixing 3D mode, startup motor protection was inadvertently disabled which unfortunately lead to a couple fried ESCs and AIOs in 0.20. 
-  The bugfixes for startup motor protection appear to have an impact on 3d performance again - see Known Issues

**Comment by hyp0dermik-code** [comment]
I think adding information about the changes to ZCD to here makes the most sense https://github.com/bird-sanctuary/bluejay/wiki/Demag-events#what-changed-in-bluejay-020

I think the related section could be minimized a bit based on the chances of this actually being a problem (using Bl32 vs AM32 as an example).

So that section could become:

- All pilots are suggested to check their tunes using their preferred method due to the improvements in zero crossing detection. See [here](https://github.com/bird-sanctuary/bluejay/wiki/Demag-events#what-changed-in-bluejay-020) for more information on what the changes mean

**Comment by stylesuxx** [comment]
Release is done - wohoo, closing this one.
