### ISSUE TITLE
Extremely slow motor ramp-up after reversing

### ISSUE THREAD

**Issue by markusgritsch** [bird-sanctuary/bluejay#97]
Bluejay 0.16 works fine.

I tried updating to newer versions, but 0.17.0, 0.18.1, and 0.19.2 all show the very strange behavior of extremely slow RPM increasing after reversing motor direction. I fly 3D and had a very unexpected crash the first time I tried flying inverted.

**Comment by stylesuxx** [comment]
Yes, unfortunately we broke 3D mode in 0.17.0, it will be fixed in 0.20.0 (See here: https://github.com/bird-sanctuary/bluejay/issues/84) until then, please stay on 0.16 for a correctly working 3D mode.

**Comment by markusgritsch** [comment]
Thanks for the clarification. So if this issue is known for over two month now, why are there no bugfix versions 0.17.1, 0.18.2, and 0.19.3? The issue is serious and causes crashes.

**Comment by markusgritsch** [comment]
But it is known for two month. If no bugfix versions were planned in this time period, at least https://esc-configurator.com/ should have pointed to mathiasvr/bluejay instead of bird-sanctuary/bluejay. Finding crash causing bugs is of little use, if no such action is taken.

**Comment by stylesuxx** [comment]
There was a version planned - we had to reduce scope though and thus there is no new release yet. As you can see, you are the first one to bring it up here. I guess you can understand from this, that 3D mode does not seem to be in wide use. If we would have had more requests, we would have rushed out a bug fix. From lack of reports we assumed low priority for this issue and thought it will be fine if fixed in the next regular release.

Again, if you want to help prevent such regressions in the future, join us on Discord and help us testing.

**Comment by stylesuxx** [comment]
Closing in favor of #81
